/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BonjourBloom {
        /**
          * The fill property of the north petal of the flower
         */
        "ratioNorth": number;
        /**
          * The fill property of the north-east petal of the flower
         */
        "ratioNorthEast": number;
        /**
          * The fill property of the north-west petal of the flower
         */
        "ratioNorthWest": number;
        /**
          * The fill property of the south petal of the flower
         */
        "ratioSouth": number;
        /**
          * The fill property of the south-east petal of the flower
         */
        "ratioSouthEast": number;
        /**
          * The fill property of the south-west petal of the flower
         */
        "ratioSouthWest": number;
    }
    interface BonjourQuestion {
        /**
          * Get the current value of the range respectively the current answer
         */
        "getValue": () => Promise<number>;
        /**
          * The maximal value
         */
        "max": number;
        /**
          * The minimal value
         */
        "min": number;
        /**
          * The default position of the range on load
         */
        "start": number;
        /**
          * How many steps between the min and the max values
         */
        "steps": number;
    }
    interface BonjourRange {
        /**
          * Get the current value of the range
         */
        "getValue": () => Promise<number>;
        /**
          * The maximal value
         */
        "max": number;
        /**
          * The minimal value
         */
        "min": number;
        /**
          * The default position of the range on load
         */
        "start": number;
        /**
          * How many steps between the min and the max values
         */
        "steps": number;
    }
}
declare global {
    interface HTMLBonjourBloomElement extends Components.BonjourBloom, HTMLStencilElement {
    }
    var HTMLBonjourBloomElement: {
        prototype: HTMLBonjourBloomElement;
        new (): HTMLBonjourBloomElement;
    };
    interface HTMLBonjourQuestionElement extends Components.BonjourQuestion, HTMLStencilElement {
    }
    var HTMLBonjourQuestionElement: {
        prototype: HTMLBonjourQuestionElement;
        new (): HTMLBonjourQuestionElement;
    };
    interface HTMLBonjourRangeElement extends Components.BonjourRange, HTMLStencilElement {
    }
    var HTMLBonjourRangeElement: {
        prototype: HTMLBonjourRangeElement;
        new (): HTMLBonjourRangeElement;
    };
    interface HTMLElementTagNameMap {
        "bonjour-bloom": HTMLBonjourBloomElement;
        "bonjour-question": HTMLBonjourQuestionElement;
        "bonjour-range": HTMLBonjourRangeElement;
    }
}
declare namespace LocalJSX {
    interface BonjourBloom {
        /**
          * The fill property of the north petal of the flower
         */
        "ratioNorth"?: number;
        /**
          * The fill property of the north-east petal of the flower
         */
        "ratioNorthEast"?: number;
        /**
          * The fill property of the north-west petal of the flower
         */
        "ratioNorthWest"?: number;
        /**
          * The fill property of the south petal of the flower
         */
        "ratioSouth"?: number;
        /**
          * The fill property of the south-east petal of the flower
         */
        "ratioSouthEast"?: number;
        /**
          * The fill property of the south-west petal of the flower
         */
        "ratioSouthWest"?: number;
    }
    interface BonjourQuestion {
        /**
          * The maximal value
         */
        "max"?: number;
        /**
          * The minimal value
         */
        "min"?: number;
        /**
          * The default position of the range on load
         */
        "start"?: number;
        /**
          * How many steps between the min and the max values
         */
        "steps"?: number;
    }
    interface BonjourRange {
        /**
          * The maximal value
         */
        "max"?: number;
        /**
          * The minimal value
         */
        "min"?: number;
        /**
          * The default position of the range on load
         */
        "start"?: number;
        /**
          * How many steps between the min and the max values
         */
        "steps"?: number;
    }
    interface IntrinsicElements {
        "bonjour-bloom": BonjourBloom;
        "bonjour-question": BonjourQuestion;
        "bonjour-range": BonjourRange;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bonjour-bloom": LocalJSX.BonjourBloom & JSXBase.HTMLAttributes<HTMLBonjourBloomElement>;
            "bonjour-question": LocalJSX.BonjourQuestion & JSXBase.HTMLAttributes<HTMLBonjourQuestionElement>;
            "bonjour-range": LocalJSX.BonjourRange & JSXBase.HTMLAttributes<HTMLBonjourRangeElement>;
        }
    }
}
